### ISSUE TITLE
allow configuration of which text field to show in foreign key combobox

### ISSUE THREAD

**Issue by beerockxs** [bstroebl/DataDrivenInputMask#16]
The database I am working with is using text fields as keys, therefore, they show up in the dropdowns when that table is referenced by a foreign key. please make it configurable which field to show in that case

**Comment by bstroebl** [comment]
Should be possible since version 2.1.0 of the plugin, I updated the wiki page accordingly, please check

**Comment by bstroebl** [comment]
Can this be closed?
