### ISSUE TITLE
configure mask does not work: Layer dd_table : PostGIS error while adding features: ERROR: null value in column "table_action" violates not-null constraint   

### ISSUE THREAD

**Issue by beerockxs** [bstroebl/DataDrivenInputMask#18]
When trying to open the configuration mask for a layer with a few non-null foreign keys, this error message appears:
Layer dd_table : PostGIS error while adding features: ERROR: null value in column "table_action" violates not-null constraint
             DETAIL: Failing row contains (6, erhaltung, netzknoten, null, null).

**Comment by beerockxs** [comment]
Ah, I think the reason is that my tables are not in the public schema, but in a different one, and the plugin is looking for the dd_table table in the wrong place.

**Comment by bstroebl** [comment]
This is a problem I already experienced in QGIS. Although the INSERT contains Nulls the fields' default values are not applied. I'll set it to true in the code.
