### ISSUE TITLE
error with multi-column foreign key

### ISSUE THREAD

**Issue by beerockxs** [bstroebl/DataDrivenInputMask#26]
I have a "nullpunkt" table with a primary key consisting of two columns "bezeichnung" (varchar of length 1) and "nummer_netzknoten" (integer) and a "ast" table that has a foreign key also consisting of two such columns ("von_nullpunkt" varchar of length 1 and "nummer_netzknoten" of type integer.

When I try to open the input mask for "nullpunkt", I get this error:

Erroneous query: SELECT * FROM "erhaltung"."ast" WHERE "von_nullpunkt" IN (39) LIMIT 0 returned 7 [ERROR: operator does not exist: character varying = integer
             LINE 1: ...CT * FROM "erhaltung"."ast" WHERE "von_nullpunkt" IN (39) LI...
              ^
             HINT: No operator matches the given name and argument type(s). You might need to add explicit type casts.
             ]

**Comment by bstroebl** [comment]
multiple FK are currently not supported. You should change nullpunkt to have **one** PK field (preferrably integer) and have ast's FK point to that PK field.
Although I know that database design allows such constructions I would always advice to have a dedicated integer field as PK and to keep that away from users.

**Comment by bstroebl** [comment]
I updated the [wiki ](https://github.com/bstroebl/DataDrivenInputMask/wiki/Precautions)to show any pitfalls.
