### ISSUE TITLE
foreign keys that are varchars do not work in search

### ISSUE THREAD

**Issue by beerockxs** [bstroebl/DataDrivenInputMask#27]
If I have a foreign key that is a varchar of length 1, searching based on that attribute does not work in the search mask, the single quotes around it are missing in the SQL query:

2019-05-02T14:17:15     CRITICAL    Layer erhaltungsabschnitt : ERROR: column "r" does not exist
             LINE 1: ...erhaltung"."erhaltungsabschnitt" WHERE "id_lage" = R LIMIT 0
              ^
Here, I have id_lage as a varchar(1) foreign key in the table erhaltungsabschnitt.

**Comment by bstroebl** [comment]
Hi,
thank you for pointing me to this problem. Something seems to be not working at all with varchar foreign keys (used to work in QGIS2, though). I cannot even show the feature form of such layers without QGIS crashing.

**Comment by bstroebl** [comment]
@beerockxs On what platform are you running QGIS?

**Comment by beerockxs** [comment]
Windows 7

Am 6. Mai 2019 09:17:06 MESZ schrieb "Bernhard Ströbl" <notifications@github.com>:
>@beerockxs On what platform are you running QGIS?
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/bstroebl/DataDrivenInputMask/issues/27#issuecomment-489521723

-- 
Sebastian Brocks
Rubensstr. 29/31
50676 Köln

**Comment by bstroebl** [comment]
@beerockxs Ok, thanks. I develop on Linux and experienced the crashes there; on Win7 with nightly build all works as expected. 
But I cannot reproduce your problem. Same as your setup:
`CREATE TABLE vm.kanten_base`
`(`
`    gid integer NOT NULL,`
`    klasse character varying(1) NOT NULL DEFAULT 'G'::character varying,`
`...`
`CONSTRAINT fk_kanten_base_klasse FOREIGN KEY (klasse)`
`        REFERENCES vm.klasse (klasse) MATCH SIMPLE`
`        ON UPDATE CASCADE`
`        ON DELETE NO ACTION`

Searching on `klasse` works as expected.
Could you please describe more in detail what you are doing and where you get the error and the SQL.

**Comment by bstroebl** [comment]
Updating QGIS on Linux stopped the application from crashing.

**Comment by beerockxs** [comment]
I have these three tables:

CREATE TABLE erhaltung.netzknoten(
	nummer integer NOT NULL,
	geometrie geometry(POINT, 3035) NOT NULL,
	name varchar(255) NOT NULL,
	id_knotenpunktfunktion varchar(2),
	id_zustand char,
	CONSTRAINT netzknoten_pk PRIMARY KEY (nummer)
);

CREATE TABLE erhaltung.zustand(
	id char NOT NULL,
	erlaeuterung text,
	CONSTRAINT zustand_pk PRIMARY KEY (id)
);

CREATE TABLE erhaltung.knotenpunktfunktion(
	id varchar(2) NOT NULL,
	erlaeuterung text,
	CONSTRAINT knotenpunktfunktion_pk PRIMARY KEY (id)
);

Searching on netzknoten using id_knotenpunktfunktion as search criterium works, using id_zustand, I get the following error message in the PostGIS message log:

2019-05-06T12:38:30     WARNING    Erroneous query: SELECT * FROM "erhaltung"."netzknoten" WHERE "id_zustand" = B LIMIT 0 returned 7 [ERROR: column "b" does not exist
             LINE 1: ...FROM "erhaltung"."netzknoten" WHERE "id_zustand" = B LIMIT 0
              ^
             ]

**Comment by bstroebl** [comment]
@beerockxs I can reproduce the issue now. Generally when you have lookup tables you should make `erlaeuterung` NOT NULL. Thus you get a comboBox with the `erlaeuterung` values, see [foreign key input](https://github.com/bstroebl/DataDrivenInputMask/wiki/Simple-Widgets)
