### ISSUE TITLE
cannot load App for classFactory() and QVariant Error

### ISSUE THREAD

**Issue by schwabenalb** [bstroebl/DataDrivenInputMask#35]
seit Neuinstallation von QGIS 3 kann ich die Erweiterung nicht mehr nutzen. Beim Aktivieren erscheint nachfolgende Fehlermeldung:

Konnte Erweiterung 'DataDrivenInputMask' nicht laden aufgrund eines Fehlers beim Aufruf der classFactory() Methode 

TypeError: 'QVariant' object is not subscriptable 
Traceback (most recent call last):
  File "C:\OSGeo4W/apps/qgis/./python\qgis\utils.py", line 423, in _startPlugin
    plugins[packageName] = package.classFactory(iface)
  File "C:\Users/WARSOW/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\DataDrivenInputMask\__init__.py", line 29, in classFactory
    return DataDrivenInputMask(iface)
  File "C:\Users/WARSOW/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\DataDrivenInputMask\datadriveninputmask.py", line 53, in __init__
    locale = QtCore.QSettings().value("locale/userLocale")[0:2]
TypeError: 'QVariant' object is not subscriptable

meine Version ist QGIS 3.22.2 auf Win10

**Comment by bstroebl** [comment]
Hallo,
in order to enable all users that might have the same issue to follow this discussion, I would prefer to continue in English.
I have the same setting here (QGIS 3.22.2 on Win10) and cannot reproduce the error.
Please open the Python console in QGIS and enter
`QtCore.QSettings().value("locale/userLocale")[0:2]`
What happens? What country is set in Windows?

**Comment by schwabenalb** [comment]
thank you for your fast response. 
your recommended python query  responds 'de'

Win10 country is Germany. 
to be precise: Win10 and qgis have been new installed on this PC. datadriveninputmask has never been active on this PC before. 
but I had the same setting on other PCs in the past, where the problem did not appear.

**Comment by bstroebl** [comment]
do any other plugins load?
see https://issues.qgis.org/issues/21464

**Comment by schwabenalb** [comment]
Thank you, 

to check the 'override system locale' settings option did solve the problem apparently, despite there was no problem with other plugins.
