### ISSUE TITLE
Plugin does not work since QGIS 3.30 because of chances in the QgsAction class

### ISSUE THREAD

**Issue by danceb** [bstroebl/DataDrivenInputMask#38]
The definition of `ActionType` within the `QgsActon` class have chanced with QGIS 3.30: https://qgis.org/pyqgis/master/gui/Qgis.html#qgis.gui.Qgis.AttributeActionType.

So setting it to the integer `1`  as done in https://github.com/bstroebl/DataDrivenInputMask/blob/master/ddmanager.py#L359 does not work anymore.

So my recommandation would be to check for the QGIS version and define the `actionType` regarding this, for instance like this:

```python
qgis_v = Qgis.QGIS_VERSION_INT
if qgis_v >= 33000:
    actionType =  QgsAction.GenericPython
else:
    actionType = 1  # actionType 1: Python

newAction = QgsAction(actionType,  actionName,
    "app=QgsApplication.instance();ddManager=app." + ddManagerName +
    ";ddManager.showDdForm([% $id %]);", newIcon, False, newTitle, {'Field', 'Feature', 'Canvas'})
```

**Comment by bstroebl** [comment]
Fixed with new version of the plugin

**Comment by bstroebl** [comment]
closed
