### ISSUE TITLE
Support using schemas other than public

### ISSUE THREAD

**Issue by ar-jan** [bstroebl/DataDrivenInputMask#4]
I have my PostgreSQL setup to use a schema other than `public` for my data. When I try to initialize a layer with DataDrivenInputMask I get `Database Error: ERROR: permission denied for schema public LINE 1: CREATE TABLE "public"."dd_table" ( "id" SERIAL N... ^ (42501) QPSQL: Unable to create query`.

Ideally DataDrivenInputMask would try to use the same schema as where the layer is stored.

**Comment by bstroebl** [comment]
Hi,
for customization of the mask the plugin creates a couple of tables in _public_ (same as QGIS does, e.g. when storing styles in the database). These tables contain customization information for **all** tables in the database, no matter in which schema they are in. Besides: we cannot assume `create table` rights for the user in the schema he loads data from, either.
The customization is assumed to be an administrator's job who has more rights in the database than a normal user. To avoid the error, please run the plugin once with a user that has `create table` rights in _public_ to have the tables created.

**Comment by ar-jan** [comment]
Thanks for the quick reply. Sure, that's fair enough. I haven't saved styles in postgres so far, so hadn't run into that yet - I'd actually dropped the public schema. I've restored it now, and things are working. Thanks for the useful plugin!

**Comment by bstroebl** [comment]
AFAIK public is a standard schema and can be assumed to exist, but I maybe mistaken
